### ISSUE TITLE
Exception thrown when wrong param used

### ISSUE THREAD

**Issue by Tomino2112** [alexfernandez/loadtest#106]
Hi,

command used:
```
loadtest http://somedomain.com/endpoint/ -c 10 -rps 100 -n 10000
```

loadtest throws this exception:
```
Invalid file to open with -p: true
C:\Users\ipp1\AppData\Roaming\npm\node_modules\loadtest\bin\loadtest.js:165
        options.printHelp();
               ^

TypeError: Cannot read property 'printHelp' of undefined
    at help (C:\Users\ipp1\AppData\Roaming\npm\node_modules\loadtest\bin\loadtest.js:165:9)
    at readBody (C:\Users\ipp1\AppData\Roaming\npm\node_modules\loadtest\bin\loadtest.js:147:3)
    at Object.<anonymous> (C:\Users\ipp1\AppData\Roaming\npm\node_modules\loadtest\bin\loadtest.js:81:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

I realized that this is because I used `-rps` instead of `--rps`

**Comment by alexfernandez** [comment]
Oops, thanks for the report! Solved in 1.4.4, just published. Please reopen if still present.
