### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by vis7** [alexfernandez/loadtest#236]
While installed npm package loadtest and run it got error. below are the steps to reproduce

```
sudo npm install -g loadtest
loadtest

```
Error
```
file:///usr/local/lib/node_modules/loadtest/bin/loadtest.js:111
await processAndRun(options)
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by alexfernandez** [comment]
Hi @vis7 , what version of Node.js are you using? Mind the [compatibility](https://github.com/alexfernandez/loadtest?tab=readme-ov-file#compatibility) section of the README file.
